spring.application.name=order-system-web
#1.資料庫連線設定(指向order_system資料庫)
spring.datasource.url=jdbc:mysql://localhost:3306/order_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234

#2.JPA/Hibernate 核心設定
#update 代表：當專案啟動時，Spring Boot 會自動根據 Java 類別在資料庫「建立或更新」資料表
spring.jpa.hibernate.ddl-auto=update
#在Console印出目前執行的SQL指令，對除錯有幫助
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true